### PR TITLE
Minor improvements

### PR DESCRIPTION
**Pull request by ackxolotl**

### CODE REVIEW

**Comment by emmericp** [comment]
@ixy-ci test

**Comment by ackxolotl** [comment]
@ixy-ci test

**Comment by ackxolotl** [comment]
@ixy-ci test

**Comment by Bobo1239** [comment]
Hm, i believe that error indicates a truncated pcap. Not sure how that happened and why we didn't encounter it before... Will open an ixy-ci PR tomorrow to add the ability to download the captured pcap for each test run. (Have been sitting on that patch for a while now...)

**Comment by emmericp** [comment]
the outputs don't show any traffic at all, so it's probably an empty pcap?

**Comment by emmericp** [comment]
@ixy-ci test

**Comment by emmericp** [comment]
running with new pcap download feature; note that the failure is probably in this PR not in ixy-ci because other PRs are working fine :)

**Pull request merged**
